table tbl_Calendar
	lineageTag: b7eb02b4-4edb-47ab-8ebe-7e10e40cc1e7

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0dda0287-2ef4-459b-830b-44a3d17d6900
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 9035d707-56d7-4df5-b89f-eaf6e6c6645d
			defaultHierarchy: LocalDateTable_56fd508a-5b5d-4706-b6ac-a04fc7f6dd23.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 71571e79-aaf2-401b-958e-ae2e0691752c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: a6081bbe-f860-4cbc-8299-6ca1c749f077
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 79c9e962-ae86-428d-bdce-00f6b8ce5d3e
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: string
		lineageTag: 7b7567cb-4741-4637-864b-c28447d1e555
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	partition tbl_Calendar = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\23769\Documents\PROJETS BI\Financial-Report-and-Analysis\Data_file.xlsx"), null, true),
				    tbl_Calendar_Table = Source{[Item="tbl_Calendar",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(tbl_Calendar_Table,{{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"Month", type text}, {"Day", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

